using System.Buffers.Binary;
using System.Security.Cryptography;
using DumpToolbox.Core;
using SharpCompress.Compressors.ZStandard;

namespace DumpToolbox.Core.Tests;

public sealed class KnownGapRecoveryTests
{
    [Fact]
    public async Task RedumperZeroFill55AndInvalidSectorGapIsGeneratedAndRestoredExactly()
    {
        const int imageSectors = 26;
        const int volumeSectors = 22;
        const uint rootLba = 20;
        const uint gapLba = 22;
        const int gapSectors = 4;
        string root = Path.Combine(Path.GetTempPath(), $"dumptoolbox-known-gap-{Guid.NewGuid():N}");
        Directory.CreateDirectory(root);
        string skeletonPath = Path.Combine(root, "disc.skeleton");
        string hashPath = Path.Combine(root, "disc.hash");
        string outputPath = Path.Combine(root, "resurrected.bin");
        string subcodePath = Path.Combine(root, "disc.subcode.zst");

        try
        {
            byte[] cooked = BuildMinimalIso(imageSectors, volumeSectors, rootLba);
            byte[] expectedRaw = ToRawMode1(cooked);

            // The third physical GAP sector has an invalid literal mode byte. Redumper
            // omits it from the logical GAP hash and skeleton erasure leaves it intact.
            int invalidOffset = checked((int)((gapLba + 2) * 2352));
            expectedRaw[invalidOffset + 15] = 0xE1;
            expectedRaw.AsSpan(invalidOffset + 16, 2336).Fill(0xA7);

            // A read-error replacement generated by Redumper retains sync/header and
            // fills every byte after byte 15 with 0x55.
            int generatedOffset = checked((int)((gapLba + 3) * 2352));
            expectedRaw.AsSpan(generatedOffset + 16, 2336).Fill(0x55);

            byte[] skeletonRaw = (byte[])expectedRaw.Clone();
            EraseRedumperMode1Payload(skeletonRaw, gapLba);
            EraseRedumperMode1Payload(skeletonRaw, gapLba + 1);
            EraseRedumperMode1Payload(skeletonRaw, gapLba + 3);
            await File.WriteAllBytesAsync(skeletonPath, skeletonRaw);

            byte[] logicalHashStream = new byte[3 * 2048];
            logicalHashStream.AsSpan(2 * 2048, 2048).Fill(0x55);
            string gapSha1 = Sha1(logicalHashStream);
            await File.WriteAllTextAsync(hashPath, $"{gapSha1} GAP_{gapLba:D7}{Environment.NewLine}");
            await WriteCompressedRedumperSubcodeAsync(subcodePath, gapLba);

            var service = new SkeletonResurrectionService();
            SkeletonInspectionResult inspection = await service.InspectAsync(skeletonPath, hashPath);

            KnownGapRecoveryInfo recovery = Assert.Single(inspection.KnownGapRecoveries);
            Assert.Equal($"GAP_{gapLba:D7}", recovery.Path);
            Assert.Equal(gapSectors, recovery.SectorCount);
            Assert.Equal(3, recovery.Form1SectorCount);
            Assert.Equal(0, recovery.Form2SectorCount);
            Assert.Equal(1, recovery.PreservedSectorCount);
            Assert.Contains((long)gapLba + 3, recovery.GeneratedFill55Lbas);

            GapSubchannelEvidence evidence = Assert.Single(inspection.GapSubchannelEvidence);
            Assert.Equal($"GAP_{gapLba:D7}", evidence.GapPath);
            Assert.Contains("Zstandard", evidence.SourceFormat, StringComparison.Ordinal);
            Assert.Equal(gapSectors, evidence.FramesObserved);
            Assert.Equal(1, evidence.TrackNumber);
            Assert.Equal(1, evidence.IndexNumber);
            Assert.True(evidence.TrackIndexContinuous);
            Assert.False(evidence.HasTrackIndexBoundaryAtStart);
            Assert.Equal(1, evidence.InvalidQCrcCount);
            Assert.Contains((long)gapLba + 2, evidence.InvalidQCrcLbas);
            Assert.Equal(1, evidence.QTimeDiscontinuityCount);
            Assert.Equal((long)gapLba + 5, evidence.LeadOutStartLba);
            Assert.Equal(1, evidence.NonZeroRwFrames);
            Assert.Empty(inspection.SubchannelEvidenceWarnings);

            SkeletonResurrectionResult result = await service.ResurrectAsync(
                inspection,
                new Dictionary<string, SkeletonSourceMatch>(),
                outputPath,
                allowMissing: false);

            Assert.Equal(0, result.MissingEntries);
            Assert.Equal(expectedRaw, await File.ReadAllBytesAsync(outputPath));
        }
        finally
        {
            try { Directory.Delete(root, recursive: true); } catch { }
        }
    }

    [Fact]
    public async Task KnownGapIsNotOfferedWhenGeneratedPatternDoesNotMatchManifestSha1()
    {
        const int imageSectors = 24;
        const int volumeSectors = 22;
        const uint rootLba = 20;
        const uint gapLba = 22;
        string root = Path.Combine(Path.GetTempPath(), $"dumptoolbox-unknown-gap-{Guid.NewGuid():N}");
        Directory.CreateDirectory(root);
        string skeletonPath = Path.Combine(root, "disc.skeleton");
        string hashPath = Path.Combine(root, "disc.hash");

        try
        {
            byte[] raw = ToRawMode1(BuildMinimalIso(imageSectors, volumeSectors, rootLba));
            EraseRedumperMode1Payload(raw, gapLba);
            EraseRedumperMode1Payload(raw, gapLba + 1);
            await File.WriteAllBytesAsync(skeletonPath, raw);
            await File.WriteAllTextAsync(
                hashPath,
                $"{new string('1', 40)} GAP_{gapLba:D7}{Environment.NewLine}");

            var service = new SkeletonResurrectionService();
            SkeletonInspectionResult inspection = await service.InspectAsync(skeletonPath, hashPath);

            Assert.Empty(inspection.KnownGapRecoveries);
        }
        finally
        {
            try { Directory.Delete(root, recursive: true); } catch { }
        }
    }

    private static void EraseRedumperMode1Payload(byte[] raw, long lba)
    {
        int offset = checked((int)(lba * 2352));
        raw.AsSpan(offset + 16, 2052).Clear();
        raw.AsSpan(offset + 2076, 276).Clear();
    }

    private static async Task WriteCompressedRedumperSubcodeAsync(string path, long gapLba)
    {
        long lastLba = gapLba + 5;
        int sectorCount = checked((int)(lastLba - SubchannelTextService.RedumperFirstLba + 1));
        byte[] multiplexed = new byte[checked(sectorCount * SubchannelTextService.BytesPerSector)];

        for (long lba = gapLba - 1; lba <= gapLba + 4; lba++)
        {
            byte[] row = BuildPositionSubchannelRow(lba, track: 1, index: 1);
            if (lba == gapLba + 1)
                row[24] = 0x01;
            if (lba == gapLba + 2)
                row[19] = 0x01; // Corrupt absolute minute after CRC generation.
            WriteMultiplexedRow(multiplexed, lba, row);
        }

        byte[] leadOut = BuildPositionSubchannelRow(lastLba, track: 0xaa, index: 1);
        WriteMultiplexedRow(multiplexed, lastLba, leadOut);

        await using var output = new FileStream(path, FileMode.CreateNew, FileAccess.Write);
        await using var compressor = new CompressionStream(
            output,
            level: 3,
            bufferSize: 1024 * 1024,
            leaveOpen: true);
        await compressor.WriteAsync(multiplexed);
    }

    private static byte[] BuildPositionSubchannelRow(long lba, int track, int index)
    {
        byte[] row = new byte[SubchannelTextService.BytesPerSector];
        Span<byte> q = row.AsSpan(12, 12);
        q[0] = 0x41;
        q[1] = track == 0xaa ? (byte)0xaa : ToBcd(track);
        q[2] = ToBcd(index);
        WriteMsf(q.Slice(3, 3), Math.Max(0, lba));
        q[6] = 0;
        WriteMsf(q.Slice(7, 3), lba + 150);
        ApplyQChannelCrc(q);
        return row;
    }

    private static void WriteMultiplexedRow(byte[] destination, long lba, ReadOnlySpan<byte> row)
    {
        int sectorIndex = checked((int)(lba - SubchannelTextService.RedumperFirstLba));
        Span<byte> column = destination.AsSpan(
            checked(sectorIndex * SubchannelTextService.BytesPerSector),
            SubchannelTextService.BytesPerSector);
        for (int channel = 0; channel < 8; channel++)
        {
            int destinationMask = 0x80 >> channel;
            int rowOffset = channel * 12;
            for (int bit = 0; bit < SubchannelTextService.BytesPerSector; bit++)
            {
                if ((row[rowOffset + bit / 8] & (0x80 >> bit % 8)) != 0)
                    column[bit] |= (byte)destinationMask;
            }
        }
    }

    private static void WriteMsf(Span<byte> target, long frames)
    {
        long minute = frames / (60 * 75);
        long remainder = frames % (60 * 75);
        long second = remainder / 75;
        long frame = remainder % 75;
        target[0] = ToBcd(checked((int)minute));
        target[1] = ToBcd(checked((int)second));
        target[2] = ToBcd(checked((int)frame));
    }

    private static byte ToBcd(int value) => checked((byte)(((value / 10) << 4) | value % 10));

    private static void ApplyQChannelCrc(Span<byte> q)
    {
        ushort crc = 0;
        for (int i = 0; i < 10; i++)
        {
            crc ^= (ushort)(q[i] << 8);
            for (int bit = 0; bit < 8; bit++)
                crc = (ushort)((crc & 0x8000) != 0 ? crc << 1 ^ 0x1021 : crc << 1);
        }
        crc ^= 0xffff;
        q[10] = (byte)(crc >> 8);
        q[11] = (byte)crc;
    }

    private static byte[] BuildMinimalIso(int imageSectors, int volumeSectors, uint rootLba)
    {
        byte[] image = new byte[imageSectors * 2048];
        Span<byte> pvd = image.AsSpan(16 * 2048, 2048);
        pvd[0] = 1;
        "CD001"u8.CopyTo(pvd[1..]);
        pvd[6] = 1;
        pvd.Slice(40, 32).Fill((byte)' ');
        "KNOWN_GAP_TEST"u8.CopyTo(pvd[40..]);
        WriteBothEndian32(pvd, 80, checked((uint)volumeSectors));
        WriteDirectoryRecord(pvd, 156, rootLba, 2048, 0x02, [0]);

        Span<byte> terminator = image.AsSpan(17 * 2048, 2048);
        terminator[0] = 0xFF;
        "CD001"u8.CopyTo(terminator[1..]);
        terminator[6] = 1;

        Span<byte> directory = image.AsSpan((int)rootLba * 2048, 2048);
        WriteDirectoryRecord(directory, 0, rootLba, 2048, 0x02, [0]);
        WriteDirectoryRecord(directory, 34, rootLba, 2048, 0x02, [1]);
        return image;
    }

    private static byte[] ToRawMode1(byte[] cooked)
    {
        int sectors = cooked.Length / 2048;
        byte[] raw = new byte[sectors * 2352];
        for (int lba = 0; lba < sectors; lba++)
        {
            Iso2BinService.BuildRawSectorFromCooked(
                cooked.AsSpan(lba * 2048, 2048),
                raw.AsSpan(lba * 2352, 2352),
                lba,
                CdSectorMode.Mode1);
        }
        return raw;
    }

    private static void WriteDirectoryRecord(
        Span<byte> target,
        int offset,
        uint extentLba,
        int dataLength,
        byte flags,
        ReadOnlySpan<byte> identifier)
    {
        int length = 33 + identifier.Length + ((identifier.Length & 1) == 0 ? 1 : 0);
        Span<byte> record = target.Slice(offset, length);
        record.Clear();
        record[0] = checked((byte)length);
        WriteBothEndian32(record, 2, extentLba);
        WriteBothEndian32(record, 10, checked((uint)dataLength));
        record[25] = flags;
        record[28] = 1;
        record[31] = 1;
        record[32] = checked((byte)identifier.Length);
        identifier.CopyTo(record[33..]);
    }

    private static void WriteBothEndian32(Span<byte> target, int offset, uint value)
    {
        BinaryPrimitives.WriteUInt32LittleEndian(target.Slice(offset, 4), value);
        BinaryPrimitives.WriteUInt32BigEndian(target.Slice(offset + 4, 4), value);
    }

    private static string Sha1(ReadOnlySpan<byte> payload) =>
        Convert.ToHexString(SHA1.HashData(payload)).ToLowerInvariant();
}
